import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[mouse]
hide_when_typing = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-D", "-s", "main"]

[window]
decorations = "none"
startup_mode = "Maximized"

[font]
size = 14

